name: virtual_eye_app
description: "Real-time environmental awareness for the visually impaired."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # --- VIRTUAL EYE PACKAGES ---
  camera: ^0.11.0+1
  permission_handler: ^11.3.1
  tflite_flutter: ^0.11.0
  image: ^4.2.0
  # ADDED: For Text-to-Speech functionality
  flutter_tts: ^4.0.2
  # ADDED: For comparing lists of objects
  collection: ^1.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/ssd_mobilenet.tflite
    - assets/labels.txt

